site: yashomer1994  
title: Low Level Tinkering
description: >-
  just a minimalist, personal blog
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: IST
#repo: https://github.com/p0wex/Gesko # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: yash007
  bio: just a minimalist, personal blog
  username: yash007 # general username
  github: yashomer1994 # github username
  twitter: yash_omer # twitter username
  email: yashomer0007@gmail.com # email adress


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


